### ISSUE TITLE
Support for more than one price for a subscription

### ISSUE THREAD

**Issue by raae** [smallbets/userbase#193]
For our product we offer both monthly and yearly plans. 

It would be great if this was supported by the Userbase payment feature.

**Comment by raae** [comment]
Is it in the works? 
Not complaining, just wondering so I can plan around it.

**Comment by j-berman** [comment]
Not in the immediate works, but hoping to have it done by end of November! Have a few things in the pipeline at the moment.

**Comment by raae** [comment]
Still end of November? Again no worries, just planning around it.

**Comment by j-berman** [comment]
End of November looking challenging at the moment, we've got some big updates en route!

Mid to late December more likely at this point

**Comment by raae** [comment]
Cool, looking forward to the big updates coming 🚀

**Comment by raae** [comment]
Also could I help? I'd rather code on this repo when it comes to payments, than on my own...

**Comment by j-berman** [comment]
Help would absolutely be appreciated! Happy to take contributions :D

Will write up a proposal on necessary changes to the API (and point to areas of the code that would need to change) when I get the chance, and can go from there.

**Comment by j-berman** [comment]
@raae  There are 2 major components of this proposal that I think are doable for someone unfamiliar with the code base. If you’re still up for it, happy to guide you through them, and will take care of the rest. Added the [DOABLE] tag to ones I think are doable :)

Feedback is also welcome.

# Overview

Developers provide a Stripe subscription plan ID (or price ID) to [purchaseSubscription()](https://userbase.com/docs/sdk/purchase-subscription/) in the Userbase SDK. The Userbase server will simply validate that a user has an active subscription to *any* plan you've created in Stripe, before allowing the user to open a database on an app with payments enabled. This way developers can offer as many plans as they want, simply by providing whatever plan ID a user wants to purchase in purchaseSubscription.

## Proposed change to Userbase SDK

### purchaseSubscription - [DOABLE]

[`purchaseSubscription()`](https://userbase.com/docs/sdk/purchase-subscription/) will take a new parameter **planId** or **priceId**. One or the other is required. Can't provide both.

- it will pass the parameter to the backend in the ['PurchaseSubscription' request](https://github.com/smallbets/userbase/blob/9d8d364f1513098c6e1502bce514e2f61a135b32/src/userbase-js/src/payments.js#L62-L63).
- the backend will use this value when calling [_createStripePaymentSession](https://github.com/smallbets/userbase/blob/9d8d364f1513098c6e1502bce514e2f61a135b32/src/userbase-server/user.js#L2398), instead of the plan ID set on an app.

## Changes to the Admin Panel/Server

### Free trial - [DOABLE]

Allow admins to add a free trial, and set a number of trial days for an app in the [payments portal](https://github.com/smallbets/userbase/blob/9d8d364f1513098c6e1502bce514e2f61a135b32/src/userbase-server/admin-panel/components/Dashboard/AppUsersTable.jsx#L935). The minimum is 1, maximum is 730 (matches Stripe’s accepted values).

- Use this value when determining what the user's [trial expiration date should be](https://github.com/smallbets/userbase/blob/9d8d364f1513098c6e1502bce514e2f61a135b32/src/userbase-server/user.js#L2567)
- Optional: can also accept a string "unlimited" in case admins want to offer a free plan

### Alter existing logic and remove unused code - [CHALLENGING]

Remove or modify all code related to setting and/or reading a subscription plan on an app. Instead, we’ll simply require the subscription plan be specified in `purchaseSubscription()` as described above, and won't use a subscription plan ID tied to an app anywhere.

- In the admin panel, remove the portion of the code where the admin can [set/delete a subscription plan on an app](https://github.com/smallbets/userbase/blob/9d8d364f1513098c6e1502bce514e2f61a135b32/src/userbase-server/admin-panel/components/Dashboard/AppUsersTable.jsx#L992-L1118). Remove all code on the backend called from that section too.
- when validating a user's payment, no need to use the subscription plan set on the app at all ([here](https://github.com/smallbets/userbase/blob/9d8d364f1513098c6e1502bce514e2f61a135b32/src/userbase-server/user.js#L2582) and [here](https://github.com/smallbets/userbase/blob/9d8d364f1513098c6e1502bce514e2f61a135b32/src/userbase-server/user.js#L2586)). Checking that the user's subscription status is set to active is good enough.
- no need to check that the app's subscription plan matches a subscription plan the user purchased before [updating the user's subscription in DynamoDB](https://github.com/smallbets/userbase/blob/9d8d364f1513098c6e1502bce514e2f61a135b32/src/userbase-server/user.js#L2489-L2495)
- no need to check that an app has a subscription plan set when building a user result [here](https://github.com/smallbets/userbase/blob/9d8d364f1513098c6e1502bce514e2f61a135b32/src/userbase-server/user.js#L1364) and [here](https://github.com/smallbets/userbase/blob/9d8d364f1513098c6e1502bce514e2f61a135b32/src/userbase-server/user.js#L1377)
- don't return app's Plan ID's in the app result [here](https://github.com/smallbets/userbase/blob/9d8d364f1513098c6e1502bce514e2f61a135b32/src/userbase-server/app.js#L412) and [here](https://github.com/smallbets/userbase/blob/9d8d364f1513098c6e1502bce514e2f61a135b32/src/userbase-server/app.js#L414)
- no need to handle the webhook event ['plan.updated' for updated Stripe subscription plans](https://github.com/smallbets/userbase/blob/9d8d364f1513098c6e1502bce514e2f61a135b32/src/userbase-server/stripe.js#L314-L323), and all code called from there. This was used to set and update app trial plans. As mentioned in the prior section, admins will set trial periods in the admin panel.
- remove the [subscription plan ID index](https://github.com/smallbets/userbase/blob/9d8d364f1513098c6e1502bce514e2f61a135b32/src/userbase-server/setup.js#L195-L232) on apps in DynamoDB

**Comment by j-berman** [comment]
Done! Recommend using the latest client userbase-js v2.5.0

**Comment by notrab** [comment]
Epic work @j-berman !

**Comment by j-berman** [comment]
Thanks @notrab 😀

Closing this issue! Feel free to follow up with any questions anyway. Hope everyone likes it!

And thanks for creating @raae !!
