### ISSUE TITLE
How can i insert nested data into the database?

### ISSUE THREAD

**Issue by sebastianbachmann** [smallbets/userbase#195]
Hi, not really an issue but a question.

I want to build an app where a coach can write progress reports for his clients, and I am absolutely not sure how to model this.

In #142 i've read that it is totally ok, to have more than one database.

Does this mean, in my case, i can create two databases - one for the clients, one for the progress reports - and connect them somehow?

As far as i understand the [_insertItem_](https://userbase.com/docs/sdk/insert-item/) documentation, it's possible to specify only one database at a time. So my Workflow would be, to have some kind of a details page for every client where i can create the progress reports?

Thanks in advance for your help!

**Comment by j-berman** [comment]
You could do something like this:

1. Your coaches could create databases called `"Progress Reports - <Client Name>"` via [openDatabase](https://userbase.com/docs/sdk/open-database/).

2. They could then insert progress reports using [insertItem](https://userbase.com/docs/sdk/insert-item/) + [uploadFile](https://userbase.com/docs/sdk/upload-file/).

3. Coaches could then share the database with their clients via [shareDatabase](https://userbase.com/docs/sdk/share-database/).

4. Clients would then be able to see progress reports shared with them via [getDatabases](https://userbase.com/docs/sdk/get-databases/).

5. Clients could then call openDatabase with the progress report’s database ID.

That make sense?

**Comment by j-berman** [comment]
Maybe your coaches would have an additional database called `"Clients"` where they store client names + contact info as well.

**Comment by j-berman** [comment]
You got it!

Userbase uses a combination of AWS DDB and S3, but I don't think that helps you very much because the API completely abstracts that away from you. You only need to understand [these](https://userbase.com/docs/sdk/#sdk-data) functions really.

 [This section](https://github.com/encrypted-dev/userbase/blob/424b11675a858fbcf67300d5b1b21033a5be04f0/docs/userbase_architecture.md#2---process-view) of the architecture spec might be a bit more helpful explaining what happens under the hood when you call these functions.

**Comment by j-berman** [comment]
Closing! Feel free to ask questions whenever
